name: infusetax_mobile
description: "InfuseTax - Modern Tax Compliance, GST, ITR & E-Governance Mobile Counter POS"
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.2
  qr_flutter: ^4.1.0
  intl: ^0.19.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  flutter_secure_storage: ^9.2.2
  blue_thermal_printer: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/brand/
